import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import userPool from "@/userPool";
import React, { useState } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [signupData, setSignupData] = useState({
    loginId: "",
    loginPw: "",
  });

  const router = useRouter();

  const inputData = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { value, name } = e.target;
    setSignupData((prev) => ({ ...prev, [name]: value }));
  };
  console.log(signupData);

  const onSignUp = () => {
    userPool.signUp(
      signupData.loginId,
      signupData.loginPw,
      [],
      [],
      (err, data) => {
        if (err) {
          return console.log(err);
        }
        alert("가입완료");
        router.push("/verify");
      }
    );
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.box}>
          <div className={styles.title}>{"회원가입"}</div>
          <div className={styles.formBox}>
            <div className={styles.idBox}>
              <p>{"아이디: "}</p>
              <input
                name="loginId"
                onChange={(e) => inputData(e)}
                type="text"
              />
            </div>
            <div className={styles.pwBox}>
              <p>{"비밀번호: "}</p>
              <input
                name="loginPw"
                onChange={(e) => inputData(e)}
                type="text"
              />
            </div>
            <button onClick={onSignUp} className={styles.button}>
              {"회원가입"}
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
