import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import userPool from "@/userPool";
import React, { useState } from "react";
import { useRouter } from "next/router";
import { CognitoUser } from "amazon-cognito-identity-js";

export default function Verify() {
  const [verifyData, setVerifyData] = useState({
    loginId: "",
    code: "",
  });

  const inputData = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { value, name } = e.target;
    setVerifyData((prev) => ({ ...prev, [name]: value }));
    console.log(verifyData);
  };

  const onVerify = () => {
    const userData = {
      Username: verifyData.loginId,
      Pool: userPool,
    };
    const cognitoUser = new CognitoUser(userData);

    cognitoUser.confirmRegistration(
      verifyData.code,
      true,
      async (err, result) => {
        if (err) {
          console.log(err);
          return;
        }
        alert("인증 성공!!!");
      }
    );
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.box}>
          <div className={styles.title}>{"인증 단계"}</div>
          <div className={styles.formBox}>
            <div className={styles.idBox}>
              <p>{"아이디: "}</p>
              <input
                name="loginId"
                onChange={(e) => inputData(e)}
                type="text"
              />
            </div>
            <div className={styles.pwBox}>
              <p>{"코드: "}</p>
              <input name="code" onChange={(e) => inputData(e)} type="text" />
            </div>
            <button onClick={onVerify} className={styles.button}>
              {"인증"}
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
